<?php
/**
 * @file
 * Code for the ICT Users feature.
 */

include_once 'ict_users.features.inc';

/**
 * Implements hook_email_registration_name().
 */
function ict_users_email_registration_name($edit, $account) {
  $email = $account->mail;
  return reset(explode('@', $email));
}

/**
 * Implements hook_forms().
 */
function ict_users_forms($form_id, $args) {
  return array(
    'ict_users_register_form' => array(
      'callback' => 'ict_user_register_form',
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function ict_users_form_alter (&$form, &$form_state, $form_id) {
  global $user;

  if ($form_id == 'user_pass_reset') {
    $form['#attributes']['class'][] = 'project-update-submission';
    $form['#prefix'] = '<div class="wrap cf" id="inner-content">';
    $form['#suffix'] = '</div>';
    $form['actions']['#attributes']['class'][] = 'submit';
  }
  if ($form_id == 'ict_users_register_form') {
    $form['account']['status']['#default_value'] = array('1');
    $form['account']['status']['#access'] = TRUE;

    $form['#validate'][] = 'ict_users_register_form_email_validation';
    $form['#validate'][] = 'ict_users_profile_departmental_admin_validate';

    $form['#prefix'] = '<div id="inner-content" class="wrap cf">
          <h2>' . t('Create a new account') . '</h2>
          <div class="register-form d-1of2">';
    $form = ict_update_update_form_recursive('#title_display', 'invisible', $form);
    $form['field_department']['#empty_value'] = FALSE;
    $form['actions']['submit']['#value'] = t('Invite User');

    $department_id = $form_state['values']['field_department']['und'][0]['tid'];
    if (user_has_role(ICT_DEPARTMENT_ADMIN_ROLE)) {
      $user = user_load($user->uid);
      $department_id = $user->field_department['und'][0]['tid'];
      $form['field_department']['und']['#value'] = $department_id;
      $form['field_department']['#disabled'] = TRUE;
    }
    else {
      $form['field_department']['und']['#required'] = TRUE;
      $form['field_department']['und']['#ajax'] = array(
        'callback' => 'ict_user_update_department_mail',
        'wrapper' => 'ict-user-update-department-mail-wrap',
        'method' => 'replace',
        'effect' => 'fade',
      );
      $form['account']['mail']['#prefix'] = '<div id="ict-user-update-department-mail-wrap">';
      $form['account']['mail']['#suffix'] = '</div>';
    }
    $department_term = taxonomy_term_load($department_id);
    $allowed_domains = ict_users_get_allowed_domains($department_term);
    $form['account']['mail']['#description'] = '';
    if (!empty($allowed_domains[0])) {
      $form['account']['mail']['#description'] = t('Accepted email domains for this department:') . ' <strong>' . implode(', ', $allowed_domains) . '</strong>';
    }
    unset($form['account']['pass']);
    $form['account']['notify']['#value'] = TRUE;

    $form['account']['name']['#description'] = '';
    $form['account']['name']['#custom_structure'] = TRUE;
    $form['account']['mail']['#custom_structure'] = TRUE;
    $form['account']['mail']['#title'] = t('Email address');

    $form['#suffix'] = '</div></div>';
    array_unshift($form['#validate'], 'ict_users_register_form_add_username_value');
    $form['account']['name']['#required'] = FALSE;
    $form['account']['name']['#validated'] = FALSE;
  }
  if ($form_id == 'user_register_form') {
    $form['#validate'][] = 'ict_users_register_form_email_validation';
    $form['#validate'][] = 'ict_users_profile_departmental_admin_validate';

    $department_id = $form_state['values']['field_department']['und'][0]['tid'];
    $form['field_department']['und']['#required'] = TRUE;
    $form['field_department']['und']['#ajax'] = array(
      'callback' => 'ict_user_update_department_mail',
      'wrapper' => 'ict-user-update-department-mail-wrap',
      'method' => 'replace',
      'effect' => 'fade',
    );
    $form['account']['mail']['#prefix'] = '<div id="ict-user-update-department-mail-wrap">';
    $form['account']['mail']['#suffix'] = '</div>';
    $department_term = taxonomy_term_load($department_id);
    $allowed_domains = ict_users_get_allowed_domains($department_term);
    $form['account']['mail']['#description'] = '';
    if (!empty($allowed_domains[0])) {
      $form['account']['mail']['#description'] = t('Accepted email domains for this department:') . ' <strong>' . implode(', ', $allowed_domains) . '</strong>';
    }
  }
  else if ($form_id == 'user_profile_form') {
    $form['#validate'][] = 'ict_users_register_form_email_validation';
    $form['#validate'][] = 'ict_users_profile_departmental_admin_validate';
    if (!user_has_role(ICT_FINANCE_ADMIN_ROLE) && $user->uid != 1) {

      $form['field_department']['#disabled'] = TRUE;
    }
  }
}


function ict_user_register_form($form, &$form_state) {
  global $user;

  $admin = user_access('administer users');

  // Pass access information to the submit handler. Running an access check
  // inside the submit function interferes with form processing and breaks
  // hook_form_alter().
  $form['administer_users'] = array(
      '#type' => 'value',
      '#value' => $admin,
  );

  // If we aren't admin but already logged on, go to the user page instead.
  if ((!$admin && $user->uid) && (!array_key_exists(ICT_DEPARTMENT_ADMIN_ROLE, $user->roles))) {
    drupal_goto('user/' . $user->uid);
  }
  $form['#user'] = drupal_anonymous_user();
  $form['#user_category'] = 'register';

  $form['#attached']['library'][] = array('system', 'jquery.cookie');
  $form['#attributes']['class'][] = 'user-info-from-cookie';

  // Start with the default user account fields.
  user_account_form($form, $form_state);

  // Attach field widgets, and hide the ones where the 'user_register_form'
  // setting is not on.
  $langcode = entity_language('user', $form['#user']);
  field_attach_form('user', $form['#user'], $form, $form_state, $langcode);
  foreach (field_info_instances('user', 'user') as $field_name => $instance) {
    if (empty($instance['settings']['user_register_form'])) {
      $form[$field_name]['#access'] = FALSE;
    }
  }

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Create new account'),
  );

  $form['#validate'][] = 'user_register_validate';
  // Add the final user registration form submit handler.
  $form['#submit'][] = 'user_register_submit';

  return $form;
}

function ict_users_register_form_add_username_value(&$form, &$form_state) {
  $form['account']['name']['#value'] = reset(explode('@', $form_state['values']['mail']));
  $form_state['values']['name'] = reset(explode('@', $form_state['values']['mail']));
}

/**
 * Implements hook_menu().
 */
function ict_users_menu_alter(&$items) {
  $items['admin/help']['access callback'] = 'ict_users_is_admin';
}

function ict_users_is_admin() {
  global $user;

  return !user_has_role(ICT_ADMINISTRATOR_ROLE, $user) ? FALSE : TRUE;
}


function ict_user_update_department_mail($form, &$form_state) {
  return $form['account']['mail'];
}

function ict_users_get_allowed_domains($term) {
  $domains_text = $term->field_acceptable_email_domains['und'][0]['value'];
  $domains = explode(',', $domains_text);
  $domains = array_map('trim', $domains);

  return $domains;
}

/**
 * Make sure that provided email belongs to the AU government
 *
 * @param $form
 * @param $form_state
 */
function ict_users_register_form_email_validation ($form, &$form_state) {
  $values = $form_state['values'];

  function endsWith($haystack, $needle) {
    $length = strlen($needle);
    if ($length == 0) {
      return true;
    }
    return (substr($haystack, -$length) === $needle);
  }

  $department_id = $form_state['values']['field_department']['und'][0]['tid'];
  $department_term = taxonomy_term_load($department_id);
  if (!ict_project_validate_email_department($values['mail'], $department_term)) {
    form_set_error('mail', t('Email doesn\'t belong to department.'));
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ict_users_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && in_array($plugin_type, array('content_types'))) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function ict_users_theme($existing, $type, $theme, $path) {
  return array(
    'ict_users_add_new_form' => array(
      'template' => 'ict-users-add-new-form',
      'path' => drupal_get_path('module', 'ict_users') . '/theme',
      'render element' => 'form',
    ),
  );
}

/**
 * Make sure that Departmental Admin is assigned to a department
 *
 * @param $form
 * @param $form_state
 */
function ict_users_profile_departmental_admin_validate ($form, &$form_state) {
  $values = $form_state['values'];
  $department_admin_role_id = user_role_load_by_name('Departmental Admin')->rid;

  if (($values['roles'][$department_admin_role_id] || $values['roleassign_roles'][$department_admin_role_id]) &&
    empty($values['field_department'][LANGUAGE_NONE][0]['tid'])) {
    form_set_error('field_department][und', t('Departmental Admin should be assigned to a department.'));
  }
}

/**
 * Implements hook_user_login().
 */
function ict_users_user_login(&$edit, $account) {
  $edit['redirect'] = '/projects';
}