<?php
/**
 * @file
 * Code for the ICT Departments feature.
 */

include_once 'ict_departments.features.inc';


function ict_department_get_department_tid_of_entity($bundle, $entity ) {

  if ($bundle == 'project') {
    return $entity->field_department[LANGUAGE_NONE][0]['tid'];
  }

  if ($bundle == 'user') {
    $entity = isset($entity->field_department) ?
      $entity :
      user_load($entity->uid);
    return
      !empty($entity->field_department[LANGUAGE_NONE][0]['tid']) ?
        $entity->field_department[LANGUAGE_NONE][0]['tid'] :
        FALSE;
  }

  return FALSE;
}
