<?php
/**
 * @file
 * Code for the ICT Update feature.
 */

/**
 * @file
 * Code for the ICT VIZ feature.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function ict_viz_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && in_array($plugin_type, array('content_types', 'access'))) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function ict_viz_theme($existing, $type, $theme, $path) {
  return array(
    'ict_viz_home_projects' => array(
      'template' => 'ict-viz-home-projects',
      'path' => drupal_get_path('module', 'ict_viz') . '/theme',
    ),
    'ict_viz_number_indicators' => array(
      'path' => drupal_get_path('module', 'ict_viz') . '/theme',
      'template' => 'ict-viz-number-indicators',
    ),
  );
}

function template_preprocess_ict_viz_home_projects(&$vars) {
  $get = $_GET;
  unset($get['q']);
  $col_classes = array(
    array(),
    array(),
    array(),
    array(),
    array(),
  );

  drupal_add_js(drupal_get_path('module', 'ict_viz') . '/js/projects_viz_table.js');

  // Get available statuses
  $statuses_info = field_info_field('field_schedule_status_calc');
  $vars['statuses'] = $statuses_info['settings']['allowed_values'];

  // Project query
  $query = db_select('node', 'project');
  $query->distinct();
  $query->join('field_data_field_project', 'update_node', 'project.nid = update_node.field_project_target_id');
  $query->leftJoin('field_data_field_expenditure_budget_calc', 'budget', 'project.nid = budget.entity_id');
  $query->leftJoin('field_data_field_expenditure_to_date_calc', 'to_date', 'project.nid = to_date.entity_id');
  $query->leftJoin('field_data_field_number_of_benefits_calc', 'benefits', 'project.nid = benefits.entity_id');
  $query->leftJoin('field_data_field_schedule_status_calc', 'status', 'project.nid = status.entity_id');
  $query->leftJoin('field_data_field_department', 'dep', 'project.nid = dep.entity_id');
  $query->leftJoin('taxonomy_term_data', 'term', 'dep.field_department_tid = term.tid');
  $query->leftJoin('field_data_field_abbreviation', 'abbr', 'term.tid = abbr.entity_id');
  $query->leftJoin('project_workflow', 'workflow', 'update_node.entity_id = workflow.nid');
  $query->fields('project');
  $query->addField('term', 'tid', 'dep_tid');
  $query->addField('budget', 'field_expenditure_budget_calc_value');
  $query->addField('to_date', 'field_expenditure_to_date_calc_value');
  $query->addField('benefits', 'field_number_of_benefits_calc_value');
  $query->addField('status', 'field_schedule_status_calc_value');
  $query->addExpression('IF(LENGTH(abbr.field_abbreviation_value) > 0, field_abbreviation_value, term.name)', 'dep_name');
  $query->condition('workflow.state', 'approved');
  $query->condition('project.type', 'project');

  // Sorting options
  $sorting = array(
    'dep_name' => 'dep_name',
    'title' => 'title',
    'budget' => 'to_date.field_expenditure_to_date_calc_value',
    'benefits' => 'benefits.field_number_of_benefits_calc_value',
    'status' => 'status.field_schedule_status_calc_value',
  );

  $sorting_labels = array(
    'dep_name' => t('Entity'),
    'title' => t('Title'),
    'budget' => t('Expenditure to Date'),
    'benefits' => t('No. of Benefits'),
    'status' => t('Project Schedule Status'),
  );

  $direction = isset($get['direction']) ? $get['direction'] : 'desc';
  if (isset($sorting[$get['order']])) {
    $table_header = t('Projects by @LABEL', array('@LABEL' => $sorting_labels[$get['order']]));
    $query->orderBy($sorting[$get['order']], $direction);
    $col_classes[array_search($get['order'], array_keys($sorting))][] = 'current_sort';
  }
  else {
    $table_header = t('Recent Projects');
    $query->orderBy('created', $direction);
  }
  $vars['table_header'] = $table_header;

  // Pager configs
  $count = $query->execute()->rowCount();
  $pager = array(
    '10' => '10',
    '25' => '25',
    '50' => '50',
    '0' => '0',
  );
  $per_page = isset($get['per_page']) && isset($pager[$get['per_page']]) ? $pager[$get['per_page']] : reset($pager);
  $page = pager_default_initialize($count, $per_page);
  $vars['pager'] = array(
    '#title' => t('Display'),
    '#type' => 'select',
    '#options' => $pager,
    '#value' => $per_page,
    '#attributes' => array('class' => array('ict-projects-table-perpage')),
  );
  $vars['pager']['#options']['0'] = 'All';
  if ($per_page) {
    $query->range($page * $per_page,$per_page);
  }

  // Get results
  $results = $query->execute()->fetchAll();
  foreach ($results as &$row) {
    $div = $row->field_expenditure_to_date_calc_value/$row->field_expenditure_budget_calc_value;
    if ($div <= 1) {
      $row->to_date_percent = $div * 100;
      $row->budget_percent = 100;
    }
    else {
      $row->to_date_percent = 100;
      $row->budget_percent = 100 / $div;
    }
  }
  $vars['results'] = $results;

  $vars['col_classes'] = array_map(function($var) { return implode(' ', $var); }, $col_classes);

  $tmp_get = $get;
  unset($tmp_get['per_page']);
  drupal_add_js(array('ict' => array('base_path' => url(current_path(), array('query' => $tmp_get)))), 'setting');

  $direction = isset($get['direction']) && $get['direction'] == 'desc' ? 'asc' : 'desc';
  $get['direction'] = $direction;
  $vars['query'] = $get;
}
