<?php
/**
 * @file
 * ict_pages.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function ict_pages_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'bean-opt_out_policy-field_description'.
  $field_instances['bean-opt_out_policy-field_description'] = array(
    'bundle' => 'opt_out_policy',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'bean',
    'field_name' => 'field_description',
    'label' => 'Body',
    'required' => 1,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Body');

  return $field_instances;
}
