<?php
/**
 * @file
 * Code for the ICT mail feature.
 */

include_once 'ict_mail.features.inc';

function ict_mail_mail($key, &$message, $params) {
  global $base_url;

  if (!empty($params['dep_admins'])) {
    $dep_name = implode(', ', array_map(function($val){ return $val['name']; }, $params['dep_admins']));
  }
  $message['body'] = array(t("Dear @NAME,", array('@NAME' => $params['name'])));
  switch($key) {
    case 'approver_add':
      $message['subject'] = t('ICT Projects Dashboard - Assigned as Project Approver');
      $message['body'][] = t("You have been assigned to the @BASELINE_TYPE @PROJ_TITLE as the Project Approver.", array('@PROJ_TITLE' => $params['title'], '@BASELINE_TYPE' => !empty($param['rebaseline']) ? 're-baselined project' : 'project'));
      $message['body'][] = t("You will receive an e-mail notification when the baseline is ready for your approval. To view who is the assigned Project Editor please log into your ICT Projects Dashboard account. !URL", array('!URL' => $base_url));
      $message['body'][] = t("Please contact your Departmental Administrator @ADMIN_NAME if you have any queries.", array('@ADMIN_NAME' => $params['admin_name']));
      break;

    case 'approver_remove':
      $message['subject'] = t('ICT Projects Dashboard - Remove as Project Approver');
      $message['body'][] = t("You have been removed from the project @PROJ_TITLE as the Project Approver.", array('@PROJ_TITLE' => $params['title']));
      $message['body'][] = t("Please contact your Departmental Administrator @ADMIN_NAME if you have any queries.", array('@ADMIN_NAME' => $params['admin_name']));
      break;

    case 'editor_add':
      $message['subject'] = t('ICT Projects Dashboard - Assigned as Project Editor');
      $message['body'][] = t("You have been assigned to the @BASELINE_TYPE @TITLE as the Project Editor. Please log into your ICT Projects Dashboard account to enter the project baseline data. !URL", array('@TITLE' => $params['title'], '!URL' => $base_url, '@BASELINE_TYPE' => !empty($param['rebaseline']) ? 're-baselined project' : 'project'));
      $message['body'][] = t("It is highly recommended that you enter and submit the baseline for approval as soon as possible after receiving this e-mail.");
      $message['body'][] = t("Please contact your Departmental Administrator @ADMIN_NAME if you have any queries.", array('@ADMIN_NAME' => $params['admin_name']));
      break;

    case 'editor_remove':
      $message['subject'] = t('ICT Projects Dashboard - Remove as Project Editor');
      $message['body'][] = t("You have been removed from the project @PROJ_TITLE as the Project Editor.", array('@PROJ_TITLE' => $params['title']));
      $message['body'][] = t("Please contact your Departmental Administrator @ADMIN_NAME if you have any queries.", array('@ADMIN_NAME' => $params['admin_name']));
      break;

    case in_array($key, array('baseline_approve_data_approvers', 'baseline_approve_data_editors')):
      $message['subject'] = t('ICT Projects Dashboard - Project Baseline Approved');
      if ($key == 'baseline_approve_data_editors') {
        $message['body'][] = t('@APPROVER_NAME has <strong>approved</strong> the baseline submission for the project @TITLE.', array('@APPROVER_NAME' => $params['approver_name'], '@TITLE' => $params['title']));
        $message['body'][] = t('@TITLE is <strong>not publicly available</strong> on the dashboard until the project\'s first update is approved.', array('@TITLE' => $params['title']));
        $plus_three_month = format_date(strtotime('+3 month'), 'medium', 'd/m/Y');
        $message['body'][] = t('You will need to update project details and submit it for approval before @3_MONTH. An update project e-mail reminder will be sent to you 1 month prior to this date.', array('@3_MONTH' => $plus_three_month));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to update and submit the project data. !URL', array('!URL' => $base_url));
      }
      elseif ($key == 'baseline_approve_data_approvers') {
        $message['subject'] = t('ICT Projects Dashboard - Baseline for the Project @TITLE is Approved', array('@TITLE' => $params['title']));
        $message['body'][] = t('@APPROVER_NAME has <strong>approved</strong> the baseline for the project @TITLE.', array('@APPROVER_NAME' => $params['approver_name'], '@TITLE' => $params['title']));
        $message['body'][] = t('No further action is required until a Project Editor submits an update on the project.');
        $message['body'][] = t('@TITLE is <strong>not publicly available</strong> on the dashboard until the project\'s first update is approved.', array('@TITLE' => $params['title']));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to view the approved baseline. !URL', array('!URL' => $base_url));
      }
      $message['body'][] = t('Please contact @APPROVER_NAME or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $dep_name));
      break;

    case in_array($key, array('baseline_request_approve_data_approvers', 'baseline_request_approve_data_editors')):
      $message['subject'] = t('ICT Projects Dashboard - Project Baseline Waiting for Approval');
      if ($key == 'baseline_request_approve_data_approvers') {
        $message['body'][] = t('@EDITOR has requested your approval for the baseline submission for the project @TITLE.', array('@EDITOR' => $params['editor_name'], '@TITLE' => $params['title']));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to review and approve the submitted project. !URL', array('!URL' => $base_url));
        $message['body'][] = t('It is highly recommended that you review and approve or submit your feedback as soon as possible after receiving this e-mail. <strong>Please note that once approved, some baseline data such as budget and original dates, cannot be changed.</strong>');
      }
      elseif ($key == 'baseline_request_approve_data_editors') {
        $message['subject'] = t('ICT Projects Dashboard - Baseline for the Project @TITLE has been submitted', array('@TITLE' => $params['title']));
        $message['body'][] = t('@EDITOR has submitted the baseline for approval for the project @TITLE.', array('@EDITOR' => $params['editor_name'], '@TITLE' => $params['title']));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to view the submitted information. !URL', array('!URL' => $base_url));
        $message['body'][] = t('No further action is required until a Project Approver approves/not approves the submitted baseline.');
      }
      $message['body'][] = t('Please contact @EDITOR or your Departmental Administrator @DEP_ADMIN if you have any queries. ', array('@EDITOR' => $params['editor_name'], '@DEP_ADMIN' => $dep_name));
      break;

    case in_array($key, array('update_request_approve_data_approvers', 'update_request_approve_data_editors')):
      $message['subject'] = t('ICT Projects Dashboard - Project Update Waiting for Approval');
      if ($key == 'update_request_approve_data_approvers') {
        $message['body'][] = t('@EDITOR has requested your approval for the update submission for the project @TITLE.', array('@EDITOR' => $params['editor_name'], '@TITLE' => $params['title']));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to review and approve the submitted project. !URL', array('!URL' => $base_url));
        $message['body'][] = t('It is highly recommended that you review and approve or submit your feedback as soon as possible after receiving this e-mail. <strong>Please note that once approved, this update data will be published on the Dashboard.</strong>');
      }
      elseif ($key == 'update_request_approve_data_editors') {
        $message['subject'] = t('ICT Projects Dashboard - An Update for the Project @TITLE has been submitted', array('@TITLE' => $params['title']));
        $message['body'][] = t('@EDITOR has submitted updates to the project @TITLE for approval.', array('@EDITOR' => $params['editor_name'], '@TITLE' => $params['title']));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to view the submitted information. !URL', array('!URL' => $base_url));
        $message['body'][] = t('No further action is required until a Project Approver approves/not approves the submitted updates.');
      }
      $message['body'][] = t('Please contact @EDITOR or your Departmental Administrator @DEP_ADMIN if you have any queries. ', array('@EDITOR' => $params['editor_name'], '@DEP_ADMIN' => $dep_name));
      break;

    case in_array($key, array('baseline_decline_data_editors', 'baseline_decline_data_approvers')):
      $message['subject'] = t('ICT Projects Dashboard - Project Baseline Not Approved');
      if ($key == 'baseline_decline_data_editors') {
        $msg = t('@APPROVER_NAME has <strong>not approved</strong> the baseline submission for the project @TITLE', array('@APPROVER_NAME' => $params['approver_name'], '@TITLE' => $params['title']));
        $msg .= !empty($params['comment']) ? t(' for the following reasons ') : '.';
        if (!empty($params['comment'])) {
          $msg .= '<em>' . nl2br($params['comment']) . '</em>';
        }
        $message['body'][] = $msg;
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to edit and resubmit the project baseline. !URL', array('!URL' => $base_url));
        $message['body'][] = t('It is highly recommended that you enter and re-submit the project updates for approval as soon as possible after receiving this e-mail.');
      }
      elseif ($key == 'baseline_decline_data_approvers') {
        $msg = t('@APPROVER_NAME has <strong>not approved</strong> the baseline for the project @TITLE', array('@APPROVER_NAME' => $params['approver_name'], '@TITLE' => $params['title']));
        $msg .= !empty($params['comment']) ? t(' for the following reasons ') : '.';
        if (!empty($params['comment'])) {
          $msg .= '<em>' . nl2br($params['comment']) . '</em>';
        }
        $message['body'][] = $msg;
        $message['subject'] = t('ICT Projects Dashboard - Baseline for the Project @TITLE is Not Approved', array('@TITLE' => $params['title']));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to view the submitted information !URL', array('!URL' => $base_url));
        $message['body'][] = t('No further action is required until a Project Editor re-submits the project baseline for approval.');
      }
      $message['body'][] = t('Please contact @APPROVER_NAME or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $dep_name));
      break;

    case in_array($key, array('update_approve_data_approvers', 'update_approve_data_editors')):
      $message['subject'] = t('ICT Projects Dashboard - Project Update Approved');
      $plus_three_month = format_date(strtotime('+3 month'), 'medium', 'd/m/Y');
      if ($key == 'update_approve_data_editors') {
        $message['body'][] = t('@APPROVER_NAME has <strong>approved</strong> the recent update submission for the project @TITLE.', array('@APPROVER_NAME' => $params['approver_name'], '@TITLE' => $params['title']));
        $message['body'][] = t('@TITLE is <strong>publicly available</strong> on the dashboard. No further action is required until your next scheduled update @3_MONTH. An update project e-mail reminder will be sent to you 1 month prior this date.', array('@3_MONTH' => $plus_three_month, '@TITLE' => $params['title']));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to update and submit the project data. !URL', array('!URL' => $base_url));
      }
      elseif ($key == 'update_approve_data_approvers') {
        $message['subject'] = t('ICT Projects Dashboard - Update to the Project @TITLE is Approved', array('@TITLE' => $params['title']));
        $message['body'][] = t('@APPROVER_NAME has <strong>approved</strong> the updates to the project @TITLE.', array('@APPROVER_NAME' => $params['approver_name'], '@TITLE' => $params['title']));
        $message['body'][] = t('Please log into your ICT Projects Dashboard account to view the submitted information. !URL', array('!URL' => $base_url));
        $message['body'][] = t('@TITLE is <strong>publicly available</strong> on the dashboard. No further action is required until the next scheduled update @3_MONTH. An update project e-mail reminder will be sent to you 1 month prior this date.', array('@3_MONTH' => $plus_three_month, '@TITLE' => $params['title']));
      }
      $message['body'][] = t('Please contact @APPROVER_NAME or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $dep_name));
      break;

    case 'update_decline_data_editors':
      $message['subject'] = t('ICT Projects Dashboard - Project Update Not Approved');
      $msg = t('@APPROVER_NAME has <strong>not approved</strong> the recent update submission for the project @TITLE', array('@APPROVER_NAME' => $params['approver_name'], '@TITLE' => $params['title']));
      $msg .= !empty($params['comment']) ? t(' for the following reasons ') : '.';
      if (!empty($params['comment'])) {
        $msg .= '<em>' . nl2br($params['comment']) . '</em>';
      }
      $message['body'][] = $msg;
      $message['body'][] = t('Please log into your ICT Projects Dashboard account to edit and resubmit the project. !URL', array('!URL' => $base_url));
      $message['body'][] = t('It is highly recommended that you enter and re-submit the project updates for approval as soon as possible after receiving this e-mail.');
      $message['body'][] = t('Please contact @APPROVER_NAME or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $dep_name));
      break;

    case 'update_decline_data_approvers':
      $message['subject'] = t('ICT Projects Dashboard - Update to the Project @TITLE is Not Approved', array('@TITLE' => $params['title']));
      $msg = t('@APPROVER_NAME has <strong>not approved</strong> the updates to the project @TITLE', array('@APPROVER_NAME' => $params['approver_name'], '@TITLE' => $params['title']));
      $msg .= !empty($params['comment']) ? t(' for the following reasons ') : '.';
      if (!empty($params['comment'])) {
        $msg .= '<em>' . nl2br($params['comment']) . '</em>';
      }
      $message['body'][] = $msg;
      $message['body'][] = t('Please log into your ICT Projects Dashboard account to view the submitted information. !URL', array('!URL' => $base_url));
      $message['body'][] = t('No further action is required until a Project Editor re-submits updates to @TITLE for approval.', array('@TITLE' => $params['title']));
      $message['body'][] = t('Please contact @APPROVER_NAME or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $dep_name));
      break;

    case 'project_create_departmental_admins':
      $message['subject'] = t('ICT Projects Dashboard - Project @TITLE is created', array('@TITLE' => $params['title']));
      $message['body'][] = t('@DEP_ADMIN has created the project @TITLE on the dashboard.', array('@DEP_ADMIN' => $dep_name, '@TITLE' => $params['title']));
      $message['body'][] = t('Please log into your ICT Projects Dashboard account to view which Project Editor(s) and Approver(s) have been assigned to the project. !URL', array('!URL' => $base_url));
      $message['body'][] = t('No further action is required. Please contact @DEP_ADMIN if you have any queries.', array('@DEP_ADMIN' => $dep_name));
      break;

    case 'project_remove_departmental_admins':
      $message['subject'] = t('ICT Projects Dashboard - Project @TITLE is removed', array('@TITLE' => $params['title']));
      $message['body'][] = t('@DEP_ADMIN has removed the project @TITLE on the dashboard.', array('@DEP_ADMIN' => $dep_name, '@TITLE' => $params['title']));
      $message['body'][] = t('No further action is required. Please contact @DEP_ADMIN if you have any queries.', array('@DEP_ADMIN' => $dep_name));
      break;

    case in_array($key, array('project_rebaselined_data_approvers', 'project_rebaselined_data_editors', 'project_rebaselined_departmental_admins')):
      $message['subject'] = t('ICT Projects Dashboard - @TITLE has been re-baselined', array('@TITLE' => $params['title']));
      $message['body'][] = t('@DEP_ADMIN has re-baselined project @TITLE.', array('@DEP_ADMIN' => $dep_name, '@TITLE' => $params['title']));
      $message['body'][] = t('Please note that project @TITLE’s details <strong>can no longer be edited</strong>.', array('@TITLE' => $params['title']));
      $message['body'][] = t('<strong>This project will remain publicly available on the dashboard until the first re-baselined project update is approved</strong>.');
      $message['body'][] = t('No further action is required.');
      $message['body'][] = t('Please contact @DEP_ADMIN if you have any queries.', array('@DEP_ADMIN' => $dep_name));
      break;

    case in_array($key, array('project_unpublished_data_approvers', 'project_unpublished_data_editors', 'project_unpublished_departmental_admins')):
      $message['subject'] = t('ICT Projects Dashboard - @TITLE has been unpublished', array('@TITLE' => $params['title']));
      $msg = t('Project @TITLE is no longer published on the ICT Projects Dashboard as of @DATE. @TITLE is unpublished', array('@DATE' => $params['unpublish_date'], '@TITLE' => $params['title']));
      $msg .= !empty($params['comment']) ? t(' for the following reasons ') : '.';
      if (!empty($params['comment'])) {
        $msg .= '<em>' . nl2br($params['comment']) . '</em>';
      }
      $message['body'][] = $msg;
      $message['body'][] = t('The unpublished project:');
      $message['body'][] = t('1) Will be removed from your project list,');
      $message['body'][] = t('2) No further changes can be made to the project,');
      $message['body'][] = t('3) Will not be included in the Dashboard calculations, and');
      $message['body'][] = t('4) Will not be represented in the Dashboard visualisations.');
      $message['body'][] = t('Please contact the Finance Administrator, @FIN_ADMIN, if you have any queries.', array('@FIN_ADMIN' => $params['fin_name']));
      break;

    case 'reminder_update_2_month':
      $message['subject'] = t('ICT Projects DashboardReminder - Update @TITLE', array('@TITLE' => $params['title']));
      $message['body'][] = t("The information on the Dashboard for the project @TITLE is approaching 3 months old. Please update @TITLE on the Dashboard as soon as possible by logging into your ICT Projects Dashboard account to update and submit the project data. !URL ", array('@TITLE' => $params['title'], '@EDITOR' => $params['editor_name'], '!URL' => $base_url));
      $message['body'][] = t('Please contact @APPROVER_NAME or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $params['depart_name']));
      break;

    case 'reminder_waiting_approval_baseline':
      $message['subject'] = t('ICT Projects DashboardReminder - Waiting for @TITLE Baseline Approval', array('@TITLE' => $params['title']));
      $message['body'][] = t('@EDITOR has requested your approval for the baseline submission for the project @TITLE on @DATE', array('@TITLE' => $params['title'], '@EDITOR' => $params['editor_name'], '@DATE' => $params['date']));
      $message['body'][] = t('Please log into you ICT Projects Dashboard account to review and approve the submitted project as soon as possible. !URL', array('!URL' => $base_url));
      $message['body'][] = t('<strong>Please note that once approved, some baseline data such as budget and original dates, cannot be changed</strong>');
      $message['body'][] = t('Please contact @EDITOR or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@EDITOR' => $params['editor_name'], '@DEP_ADMIN' => $params['depart_name']));
      break;

    case 'reminder_waiting_approval_update':
      $message['subject'] = t('ICT Projects DashboardReminder - Waiting for @TITLE Update Approval', array('@TITLE' => $params['title']));
      $message['body'][] = t('@EDITOR has requested your approval for the update submission for the project @TITLE on @DATE', array('@TITLE' => $params['title'], '@EDITOR' => $params['editor_name'], '@DATE' => $params['date']));
      $message['body'][] = t('Please log into you ICT Projects Dashboard account to review and approve the submitted project as soon as possible. !URL', array('!URL' => $base_url));
      $message['body'][] = t('<strong>Please note that once approved, this update data will be published on the Dashboard</strong>');
      $message['body'][] = t('Please contact @EDITOR or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@EDITOR' => $params['editor_name'], '@DEP_ADMIN' => $params['depart_name']));
      break;

    case 'reminder_update_3_month':
      $message['subject'] = t('ICT Projects DashboardReminder - Update @TITLE', array('@TITLE' => $params['title']));
      $message['body'][] = t('The information on the Dashboard for the project @TITLE is 3 months old. Please update @TITLE on the Dashboard <strong>today</strong> by logging into your ICT Projects Dashboard account to update and submit the project data. !URL', array('@TITLE' => $params['title'], '@EDITOR' => $params['editor_name'], '@DATE' => $params['date'], '!URL' => $base_url));
      $message['body'][] = t('Please log into you ICT Projects Dashboard account to review and approve the submitted project as soon as possible. !URL', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $params[$dep_name], '!URL' => $base_url));
      $message['body'][] = t('Please contact @APPROVER_NAME or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $params['depart_name']));
      break;

    case 'reminder_update_after':
      $message['subject'] = t('ICT Projects DashboardReminder - Update @TITLE', array('@TITLE' => $params['title']));
      $message['body'][] = t('The information on the Dashboard for the project @TITLE more than 3 months old. Please update @TITLE on the Dashboard <strong>immediately</strong> by logging into your ICT Projects Dashboard account to update and submit the project data. !URL', array('@TITLE' => $params['title'], '@EDITOR' => $params['editor_name'], '@DATE' => $params['date'], '!URL' => $base_url));
      $message['body'][] = t('Please log into you ICT Projects Dashboard account to review and approve the submitted project as soon as possible. !URL', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $params[$dep_name], '!URL' => $base_url));
      $message['body'][] = t('Please contact @APPROVER_NAME or your Departmental Administrator @DEP_ADMIN if you have any queries.', array('@APPROVER_NAME' => $params['approver_name'], '@DEP_ADMIN' => $params['depart_name']));
      break;
  }
}

function __ict_mail_process_mails($module, $hook, $node, $acc_types, $params = array(), $strict_dep_admins = TRUE) {
  global $user;

  $accs = __ict_mail_prepare_mails($node, $strict_dep_admins);
  foreach($acc_types as $type) {
    foreach ($accs[$type] as $acc) {
      if ($user->mail == $acc['mail']) continue;
      drupal_mail($module, $hook . '_' . $type, $acc['mail'], LANGUAGE_NONE, array_merge(
        array(
          'name' => $acc['name'],
          'title' => $node->title,
          'dep_admins' => $accs['departmental_admins'],
        ),
        $params
      ));
    }
  }
}

function __ict_mail_prepare_mails($node, $strict_dep_admins = TRUE) {
  $emails = ict_project_baseline_get_admin_user_emails($node);
  $accs = array();

  // get only first departmental admin
  $creator = user_load($node->uid);
  if ($strict_dep_admins) {
    if (in_array($creator->mail, $emails['departmental_admins'])) {
      $emails['departmental_admins'] = array($creator->mail);
    }
    else {
      $emails['departmental_admins'] = array(array_shift($emails['departmental_admins']));
    }
  }

  foreach($emails as $type => $mails) {
    foreach ($mails as $mail) {
      $acc = user_load_by_mail($mail);
      $accs[$type][] = array(
        'mail' => $acc->mail,
        'name' => _ict_project_get_user_name($acc),
      );
    }
  }

  return $accs;
}

/**
 * Implements hook_mail_alter()
 */
function ict_mail_mail_alter (&$message) {
  // adds security note to all emails as per Finance requirements
  $message['subject'] .= ' [SEC=UNCLASSIFIED]';

  $unclassified_content_mark  = '
    <p class="MsoNormal" align="center" style="margin-bottom:12.0pt;text-align:center">
        <b>
          <span style="font-family:”Arial”;,sans-serif;color:#999999">
              UNCLASSIFIED<br><br>
          </span>
        </b>
    </p>';

  array_push($message['body'], $unclassified_content_mark);
  array_unshift($message['body'], $unclassified_content_mark);
}
