<?php
/**
 * @file
 * Code for the ICT Project feature.
 */

include_once 'ict_project.features.inc';
require_once(DRUPAL_ROOT . "/modules/node/node.pages.inc");

/**
 * Implements hook_ctools_plugin_directory().
 */
function ict_project_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * returns add project  form
 */
function ict_project_project_add_block () {
  if (user_is_logged_in()) {
    module_load_include('inc', 'node', 'node.pages');
    $form = node_add('project');
    $form['#attached']['js'] = array(
      drupal_get_path('module', 'ict_project') . '/js/ict_project.js',
    );
    
    $form['#theme'] = 'ict_project_add_project_form';
    //hide native labels
    $form['field_government_entity_name']['und'][0]['value']['#title_display'] = $form['field_government_business_unit']['und'][0]['value']['#title_display'] =
    $form['title']['#title_display'] = $form['field_brief_project_summary']['und'][0]['value']['#title_display'] =
    $form['field_program_name']['und'][0]['value']['#title_display'] = $form['field_project_stage']['und']['#title_display'] =
    $form['field_project_category']['und']['#title_display'] = $form['field_project_manager']['und'][0]['value']['#title_display'] =
    $form['field_project_manager_email']['und'][0]['email']['#title_display'] = $form['field_total_project_budget']['und'][0]['value']['#title_display'] =
    $form['field_expected_project_benefits']['und'][0]['value']['#title_display'] = $form['field_start_date']['und'][0]['value']['day']['#title_display'] =
    $form['field_start_date']['und'][0]['value']['month']['#title_display'] = $form['field_start_date']['und'][0]['value']['year']['#title_display'] =
    $form['field_original_completion_date']['und'][0]['value']['day']['#title_display'] = $form['field_original_completion_date']['und'][0]['value']['month']['#title_display'] =
    $form['field_original_completion_date']['und'][0]['value']['year']['#title_display'] = $form['field_government_programme']['und'][0]['value']['#title_display'] =
    $form['field_implementation_partners']['und'][0]['value']['#title_display'] = $form['field_total_spent_to_date']['und'][0]['value']['#title_display'] =
    $form['field_expected_number_of_gov_fte']['und'][0]['value']['#title_display'] = $form['field_expected_num_contractors']['und'][0]['value']['#title_display'] =
      $form['field_project_users']['und']['#title_display'] = $form['field_expenditure_type']['und']['#title_display'] = $form['field_project_status']['und']['#title_display'] = $form['field_internal_fte']['und'][0]['value']['#title_display'] = $form['field_external_fte']['und'][0]['value']['#title_display'] =
      $form['field_rebaselined_total_project']['und'][0]['value']['#title_display'] = $form['field_predicted_project_benefit']['und'][0]['value']['#title_display'] =
    'invisible';

    //add 33%-width to date select elements
    $form['field_start_date']['und'][0]['value']['day']['#wrapper_class'][] = $form['field_start_date']['und'][0]['value']['month']['#wrapper_class'][] =
    $form['field_start_date']['und'][0]['value']['year']['#wrapper_class'][] = $form['field_original_completion_date']['und'][0]['value']['day']['#wrapper_class'][] =
    $form['field_original_completion_date']['und'][0]['value']['month']['#wrapper_class'][] = $form['field_original_completion_date']['und'][0]['value']['year']['#wrapper_class'][] =

    $form['field_rebaselined_project_start']['und'][0]['value']['day']['#wrapper_class'][] = $form['field_rebaselined_project_start']['und'][0]['value']['month']['#wrapper_class'][] =
    $form['field_rebaselined_project_start']['und'][0]['value']['year']['#wrapper_class'][] =

    $form['field_rebaselined_project_compl']['und'][0]['value']['day']['#wrapper_class'][] = $form['field_rebaselined_project_compl']['und'][0]['value']['month']['#wrapper_class'][] =
    $form['field_rebaselined_project_compl']['und'][0]['value']['year']['#wrapper_class'][] = 'd-1of3';


    $form['field_start_date']['und'][0]['value']['year']['#wrapper_class'][] =
    $form['field_original_completion_date']['und'][0]['value']['year']['#wrapper_class'][] =
    $form['field_rebaselined_project_start']['und'][0]['value']['year']['#wrapper_class'][] =
    $form['field_rebaselined_project_compl']['und'][0]['value']['year']['#wrapper_class'][] = 'last-col';

    $form['field_rebaselined_total_budget']['und']['#theme'] = 'ict_project_rebaselined_total_budget';
    $form['field_original_total_budget']['und']['#theme'] = 'ict_project_rebaselined_total_budget';

    //date fields (adding empty options)
    $date_fields = array(
      'field_start_date',
      'field_original_completion_date',
      'field_rebaselined_project_start',
      'field_rebaselined_project_compl',
    );

    ict_project_add_status_tooltips ($form['field_project_status']);

    foreach ($date_fields as $field) {
      $form[$field][LANGUAGE_NONE][0]['value']['day']['#options'][''] = t('Day');
      $form[$field][LANGUAGE_NONE][0]['value']['year']['#options'][''] = t('Year');
      $form[$field][LANGUAGE_NONE][0]['value']['month']['#options'][''] = t('Month');
    }

    // Start year should be set via CMS
    $start_year = variable_get('ict_dashboard_project_start_year', 13);

    foreach (element_children($form['field_rebaselined_total_budget']['und']) as $item) {
      foreach (element_children($form['field_rebaselined_total_budget']['und'][$item]) as $sub_item) {
        $form['field_rebaselined_total_budget']['und'][$item][$sub_item]['und'][0]['value']['#title_display'] = 'invisible';
      }
      $form['field_rebaselined_total_budget']['und'][$item]['field_year']['und'][0]['value']['#value'] = $start_year . '/' . ++$start_year;
    }

    // Start year should be set via CMS
    $start_year = variable_get('ict_dashboard_project_start_year', 13);

    foreach (element_children($form['field_original_total_budget']['und']) as $item) {
      foreach (element_children($form['field_original_total_budget']['und'][$item]) as $sub_item) {
        $form['field_original_total_budget']['und'][$item][$sub_item]['und'][0]['value']['#title_display'] = 'invisible';
      }
      $form['field_original_total_budget']['und'][$item]['field_year']['und'][0]['value']['#value'] = $start_year . '/' . ++$start_year;
    }

    return drupal_render($form);
  }
  else {
    drupal_not_found();
  }
}

function ict_project_add_status_tooltips (&$form) {
  $tooltips = array(
    'green' => t('The project appears likely to deliver its intended benefits, and is broadly on time and within budget.'),
    'amber' => t('The project might not deliver its intended benefits AND/OR is behind schedule AND/OR is over budget.'),
    'red' => t('The project appears unlikely to deliver its intended benefits AND/OR is significantly behind schedule AND/OR is significantly over budget.'),
  );

  foreach (element_children($form['und']) as $item) {
    $form['und'][$item]['#prefix'] = '<div class="radio-description">';
    $form['und'][$item]['#suffix'] = '<span class="corner iradius50 tooltipster-icon" title="' . $tooltips[$item] . '"'  . ' >(?)</span></div>';
  }

  $form['#attached']['css'][] = drupal_get_path('module', 'ict_project') . '/css/tooltipster.css';
  $form['#attached']['js'][] = drupal_get_path('module', 'ict_project') . '/js/jquery.tooltipster.min.js';
}


/**
 * Implement hook_preprocess().
 */
function ict_project_preprocess_ict_project_mid_project_form (&$variables){
  ict_project_add_status_tooltips ($variables['form']['field_mid_project_status']);
}


/**
 * Implement hook_preprocess().
 */
function ict_project_preprocess_ict_project_end_project_form (&$variables){
  ict_project_add_status_tooltips ($variables['form']['field_end_project_status']);
}

/**
 * Implement hook_form_alter
 */
function ict_project_form_alter( &$form, &$form_state,$form_id){

  if($form_id == 'project_node_form') {
    ksort($form['field_project_stage']['und']['#options']);
    $form['#theme'] = 'ict_project_add_project_form';
    //hide native labels
    $form['field_government_entity_name']['und']['#title_display'] = $form['field_government_business_unit']['und'][0]['value']['#title_display'] =
    $form['title']['#title_display'] = $form['field_brief_project_summary']['und'][0]['value']['#title_display'] =
    $form['field_program_name']['und'][0]['value']['#title_display'] = $form['field_project_stage']['und'][0]['value']['#title_display'] =
    $form['field_project_category']['und']['#title_display'] = $form['field_project_manager']['und'][0]['value']['#title_display'] =
    $form['field_project_manager_email']['und'][0]['value']['#title_display'] = $form['field_total_project_budget']['und'][0]['value']['#title_display'] =
    $form['field_expected_project_benefits']['und'][0]['value']['#title_display'] = $form['field_start_date']['und'][0]['value']['day']['#title_display'] =
    $form['field_start_date']['und'][0]['value']['month']['#title_display'] = $form['field_start_date']['und'][0]['value']['year']['#title_display'] =
    $form['field_original_completion_date']['und'][0]['value']['day']['#title_display'] = $form['field_original_completion_date']['und'][0]['value']['month']['#title_display'] =
    $form['field_original_completion_date']['und'][0]['value']['year']['#title_display'] = $form['field_government_programme']['und'][0]['value']['#title_display'] =
    $form['field_implementation_partners']['und'][0]['value']['#title_display'] = $form['field_total_spent_to_date']['und'][0]['value']['#title_display'] =
    $form['field_expected_number_of_gov_fte']['und'][0]['value']['#title_display'] = $form['field_expected_num_contractors']['und'][0]['value']['#title_display'] =
      'invisible';
  }

  if($form_id == 'ict_form_entityform_edit_form') {
    $default_project = ict_project_get_project_update();
    $form['field_mid_project_name']['und'][0]['value']['#type'] = 'hidden';
    $form['field_mid_project_name']['und'][0]['value']['#default_value'] = $default_project;
    $form['field_mid_project_name'][LANGUAGE_NONE][0]['value']['#attributes']['disabled'] = TRUE;
    $form['#theme'] = 'ict_project_mid_project_form';
    $form['field_mid_project_name']['und'][0]['value']['#title_display'] = $form['field_mid_project_stage']['und']['#title_display'] =            $form['field_mid_project_manager']['und'][0]['value']['#title_display'] =
    $form['field_mid_project_manager_email']['und'][0]['value']['#title_display'] =
    $form['field_mid_revised_total_project']['und'][0]['value']['#title_display'] =
    $form['field_mid_total_project_spend']['und'][0]['value']['#title_display'] =

    $form['field_mid_total_project_spend']['und'][0]['value']['#title_display'] =
    $form['field_mid_total_project_current']['und'][0]['value']['#title_display'] =
    $form['field_mid_project_completed']['und'][0]['value']['#title_display'] =
    $form['field_mid_predicted_project']['und'][0]['value']['#title_display'] =
    $form['field_mid_predicted_project_real']['und'][0]['value']['#title_display'] =
    $form['field_mid_internal_fte']['und'][0]['value']['#title_display'] =
    $form['field_mid_external_fte']['und'][0]['value']['#title_display'] =
    $form['field_mid_project_status']['und']['#title_display'] =
    $form['field_mid_agency_comments']['und'][0]['value']['#title_display'] =
    $form['field_mid_csv_file']['und'][0]['#title_display']
        = 'invisible';

    // Open the file for writing.
    $fields = array();
    $exclude = array('field_mid_project_name', 'field_mid_csv_file', 'actions', 'form_build_id', 'form_token', 'form_id');
    $sort = array();
    foreach(element_children($form) as $field) {
      if(!in_array($field, $exclude)) {
        $sort[$field] = $form[$field]['#weight'];
      }
    }
    asort($sort);

    foreach($sort as $key=>$field) {
      $fields[] = $key;
    }

    $file_path = drupal_get_path('module', 'ict_project') . '/export.csv';
    $fh = fopen($file_path, 'w');
    fputcsv($fh, $fields);
    // Close & save the file.
    fclose($fh);
    file_unmanaged_copy($file_path, $destination = NULL,  FILE_EXISTS_REPLACE);

    $form['#attached']['js'] = array(
      drupal_get_path('module', 'ict_project') . '/js/ict_project.js',
    );

    $form['field_mid_project_status']['und']['#required'] = FALSE;
    $form['actions']['submit']['#submit'][] = 'ict_project_csv_submit_form_submit';
  }

  if($form_id == 'itc_form_end_entityform_edit_form') {
    $default_project = ict_project_get_project_update();
    $form['field_end_project_name']['und'][0]['value']['#type'] = 'hidden';
    $form['field_end_project_name']['und'][0]['value']['#default_value'] = $default_project;
    $form['field_end_project_name'][LANGUAGE_NONE][0]['value']['#attributes']['disabled'] = TRUE;
    $form['#theme'] = 'ict_project_end_project_form';
    $form['field_end_project_name']['und'][0]['value']['#title_display'] =
    $form['field_end_project_stage']['und']['#title_display'] =
    $form['field_end_project_manager']['und'][0]['value']['#title_display'] =
    $form['field_end_project_manager_email']['und'][0]['value']['#title_display'] =
    $form['field_end_revised_total_project']['und'][0]['value']['#title_display'] =
    $form['field_end_total_project_spend']['und'][0]['value']['#title_display'] =
    $form['field_end_total_project_current']['und'][0]['value']['#title_display'] =
    $form['field_end_project_completed']['und'][0]['value']['#title_display'] =
    $form['field_end_predicted_project']['und'][0]['value']['#title_display'] =
    $form['field_end_predicted_realised']['und'][0]['value']['#title_display'] =
    $form['field_end_internal_fte']['und'][0]['value']['#title_display'] =
    $form['field_end_external_fte']['und'][0]['value']['#title_display'] =
    $form['field_end_project_status']['und']['#title_display'] =
    $form['field_end_agency_comments']['und'][0]['value']['#title_display'] =
    $form['field_end_csv_file']['und'][0]['#title_display'] =
      'invisible';

    ict_project_add_status_tooltips ($form['field_end_project_status']);

    // Open the file for writing.
    $fields = array();
    $sort = array();
    $exclude = array('field_end_project_name', 'field_end_csv_file', 'actions', 'form_build_id', 'form_token', 'form_id');
    foreach(element_children($form) as $field) {
      if(!in_array($field, $exclude)) {
        $sort[$field] = $form[$field]['#weight'];
      }
    }
    asort($sort);
    dsm($sort);
    foreach($sort as $key=>$field) {
      $fields[] = $key;
    }

    $file_path = drupal_get_path('module', 'ict_project') . '/export_end.csv';
    $fh = fopen($file_path, 'w');
    fputcsv($fh, $fields);
    // Close & save the file.
    fclose($fh);
    file_unmanaged_copy($file_path, $destination = NULL,  FILE_EXISTS_REPLACE);


    $form['field_end_predicted_budget']['und']['#theme'] = 'ict_project_end_predicted_budget';

    // Start year should be set via CMS
    $start_year = variable_get('ict_dashboard_project_start_year', 13);

    foreach (element_children($form['field_end_predicted_budget']['und']) as $item) {
      foreach (element_children($form['field_end_predicted_budget']['und'][$item]) as $sub_item) {
        $form['field_end_predicted_budget']['und'][$item][$sub_item]['und'][0]['value']['#title_display'] = 'invisible';
      }
      $form['field_end_predicted_budget']['und'][$item]['field_predicted_year']['und'][0]['value']['#value'] = $start_year . '/' . ++$start_year;
    }
    $form['#attached']['js'] = array(
      drupal_get_path('module', 'ict_project') . '/js/ict_project.js',
    );

    $form['field_end_project_status']['und']['#required'] = FALSE;
    $form['actions']['submit']['#submit'][] = 'ict_project_csv_submit_form_submit';

  }
}


/**
 * Implements hook_theme().
 */
function ict_project_theme () {
  return array(
    'ict_project_add_project_form' => array(
      'template' => 'ict_project_add_project_form',
      'path' => drupal_get_path('module', 'ict_project') . '/theme',
      'render element' => 'form',
    ),
    'ict_project_rebaselined_total_budget' => array(
      'template' => 'ict_project_rebaselined_total_budget',
      'path' => drupal_get_path('module', 'ict_project') . '/theme',
      'render element' => 'element',
    ),
    'ict_project_end_predicted_budget' => array(
      'template' => 'ict_project_end_predicted_budget',
      'path' => drupal_get_path('module', 'ict_project') . '/theme',
      'render element' => 'element',
    ),
    'ict_project_mid_project_form' => array(
      'template' => 'ict_project_mid_project_form',
      'path' => drupal_get_path('module', 'ict_project') . '/theme',
      'render element' => 'form',
    ),
    'ict_project_end_project_form' => array(
      'template' => 'ict_project_end_project_form',
      'path' => drupal_get_path('module', 'ict_project') . '/theme',
      'render element' => 'form',
    ),
  );
}

/**
 * Implements_hook_menu
 */
function ict_project_menu() {
  $items = array();

  $items['admin/config/project-form-settings'] = array(
    'title' => 'Project form settings',
    'description' => 'Settings page for Project form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ict_project_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Module configurations form
 */
function ict_project_admin_settings_form($form, &$form_state) {
  $form['ict_dashboard_project_start_year'] = array(
    '#type' => 'textfield',
    '#title' => t('Project start year'),
    '#default_value' => variable_get('ict_dashboard_project_start_year', 13),
    '#size' => 2,
    '#maxlength' => 2,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/*
 * Return all project
 */
function ict_project_get_project() {
  $projects = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->condition('n.type', 'project')
    ->condition('n.status', 1)
    ->execute()
    ->fetchAllKeyed();

  return $projects;
}

function ict_project_bracket_italics ($string) {
  $source = explode('(', $string);

  $string = $source[0] . '<em>(' . $source[1] . '</em>';

  return $string;
}

/*
 * Implements hook_node_insert()
 */
function ict_project_node_insert (&$node) {
  if ($node->type == 'project') {
    $node->status = 1;
  }
}



function ict_project_get_project_update() {
  global $user;
  $id = $user->uid;
  $query = db_select('node', 'n');
  $query->fields('n', array('title'));
  $query->condition('n.type', 'project', '=');
  $query->condition('n.uid', $id, '=');
  $query->orderBy('created', 'ASC');
  $projects = $query->execute()->fetchField();

  return $projects;
}



function ict_project_csv_submit_form_submit($form, &$form_state) {
  //Load file
  if($form['#form_id'] == 'itc_form_end_entityform_edit_form') {
    $file_field = 'field_end_csv_file';
  }else{
    $file_field = 'field_mid_csv_file';
  }

  $fid = $form_state['values'][$file_field][LANGUAGE_NONE][0]['fid'];
  $csv_file = file_load($fid);
  if(!empty($csv_file)) {
    //Open csv
    $handle = fopen($csv_file->uri, 'r');
    $row = fgetcsv($handle);
    //Read columns
    $columns = array();
    foreach ($row as $i => $header) {
      $columns[$i] = trim($header);
    }

    //Read value and filled field form - form state
    while ($row = fgetcsv($handle)) {
      foreach ($row as $i => $field) {
        switch ($columns[$i]) {
          case 'field_mid_project_stage':
          case 'field_mid_project_status':
          case 'field_end_project_stage':
          case 'field_end_project_status':
            $form_state['input'][$columns[$i]][LANGUAGE_NONE] = $field;
            break;
          case 'field_mid_expected_project':
          case 'field_end_expected_project':
            $date = explode('/', $field);
            $form_state['input'][$columns[$i]][LANGUAGE_NONE][0]['value']['day'] = $date[0];
            $form_state['input'][$columns[$i]][LANGUAGE_NONE][0]['value']['month'] = $date[1];
            $form_state['input'][$columns[$i]][LANGUAGE_NONE][0]['value']['year'] = $date[2];
            break;
          default:
            $form_state['input'][$columns[$i]][LANGUAGE_NONE][0]['value'] = $field;
        }
      }
    }
    drupal_set_message(t('You\'ve successfully submitted form via CSV'));
  }

}
