<?php
/**
 * @file
 * ict_project.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function ict_project_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Cultural affairs',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '041e0416-d522-40b4-9b05-ff8c68611d87',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Immigration',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '10f745a5-6dd9-4e61-87c3-1f55366a6fc8',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Closing',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '138a4c12-af0a-48c3-af74-f36ebb928d46',
    'vocabulary_machine_name' => 'project_stage',
  );
  $terms[] = array(
    'name' => 'Science',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '141d2fe0-7bce-48ba-a334-e4d98809d456',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Initiation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '188a9d4d-9f50-4c79-951d-c9e2ecdac5f7',
    'vocabulary_machine_name' => 'project_stage',
  );
  $terms[] = array(
    'name' => 'Funding source term 1',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '309d4767-fee6-4508-874b-408abec1a040',
    'vocabulary_machine_name' => 'funding_source',
  );
  $terms[] = array(
    'name' => 'Civic infrastructure',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '365ccb17-8b4c-489d-9972-62bc6127cb8c',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Health care',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3ffb40a3-b6df-4f31-9088-583872f8337d',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'International relations',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4766eb10-163a-4f5a-b082-48fa70b1edc9',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Natural resources',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '55c1af39-518b-4da3-9a0c-ded52ad1c2c9',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Primary industries',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5ba8df37-f6ce-4386-8f10-7c21de3571a8',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Business support and regulation',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '60c6ad72-aa35-4823-bec7-72d25aab1091',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Tourism',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '666afce7-7c47-422b-af17-978bb07fd8ae',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Education and training',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '77180b52-3e2a-4e5a-b184-c00297560a02',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Communications',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7e97599c-31bc-44d0-b923-5f22522e61fa',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Controlling',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '87cc2f05-50b4-466e-8989-34635eaaffca',
    'vocabulary_machine_name' => 'project_stage',
  );
  $terms[] = array(
    'name' => 'Defence',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9f6e4216-38be-4c04-a456-039ca2085128',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Trade',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a2e9a4a3-77cb-4262-857b-08c84c4d9a86',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Community services',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a9197dd3-053e-413c-a68b-4174b68ec4f7',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Governance',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b3f9374b-35a7-4587-b9d5-96c9fe1987f9',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Transport',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b9f723c7-b467-40ce-82f7-4c29cd187ce0',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Justice administration',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bc2eef23-bd89-465f-a247-29cb99e1b380',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Environment',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c0750fa0-39bc-4f96-9195-1a8b95ddd8c4',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Start up',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cbe76c93-a5d1-41ed-9408-d75995b37fb1',
    'vocabulary_machine_name' => 'project_stage',
  );
  $terms[] = array(
    'name' => 'Sport and recreation',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd18e654c-dd84-4ab1-8f32-eaeee348ac17',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Security',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd1ac5cbb-43e3-41c2-8a46-211a67eae14b',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Indigenous affairs',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dd7880f3-d379-4e7c-8102-8856d42e3c82',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Funding source term 2',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e1f00bca-bb30-496f-ade7-452340e7f365',
    'vocabulary_machine_name' => 'funding_source',
  );
  $terms[] = array(
    'name' => 'Employment',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e217c0ad-3b31-4e14-a6e3-d7b6e71c5fe5',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Finance management',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f391c628-fbc1-4d1e-8596-0a84c3186edd',
    'vocabulary_machine_name' => 'project_category',
  );
  $terms[] = array(
    'name' => 'Maritime services',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f70dfcbf-52e7-4d19-b226-f9c26657842d',
    'vocabulary_machine_name' => 'project_category',
  );
  return $terms;
}
