<?php
/**
 * @file
 * ict_user_guide.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function ict_user_guide_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "bean_admin_ui" && $api == "bean") {
    return array("version" => "5");
  }
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
